/*
 * File: app/store/LotesMysql.js
 *
 * This file was generated by Sencha Architect version 4.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.LotesMysql', {
  extend: 'Ext.data.Store',

  requires: [
    'MyApp.model.Lotes',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json'
  ],

  config: {
    sql: 'select id,codigo,descrip as nombre,superficie,cod_establecimiento from lotes'
  },

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'LotesMysql',
      model: 'MyApp.model.Lotes',
      proxy: {
        type: 'ajax',
        reader: {
          type: 'json',
          rootProperty: 'Lotes'
        }
      }
    }, cfg)]);
  }
});