/*
 * File: app/store/Lotes_actividadesMysql.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Lotes_actividadesMysql', {
  extend: 'Ext.data.Store',

  requires: [
    'MyApp.model.Lotes_actividades',
    'Ext.data.proxy.Ajax',
    'Ext.data.reader.Json'
  ],

  config: {
    sql: 'SELECT id,codigo,descripcion as nombre,cod_lote,cod_actividad,cod_periodo,fecha_desde as desde,fecha_hasta as hasta FROM lote_actividad'
  },

  constructor: function(cfg) {
    var me = this;
    cfg = cfg || {};
    me.callParent([Ext.apply({
      storeId: 'Lotes_actividadesMysql',
      model: 'MyApp.model.Lotes_actividades',
      proxy: {
        type: 'ajax',
        reader: {
          type: 'json',
          rootProperty: 'Lotes_actividades'
        }
      }
    }, cfg)]);
  }
});