/*
 * File: app/view/ActividadesForm.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ActividadesForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.actividadesform',

  requires: [
    'MyApp.view.ActividadesFormViewModel',
    'Ext.form.field.Number',
    'Ext.container.Container',
    'Ext.button.Button'
  ],

  viewModel: {
    type: 'actividadesform'
  },
  flex: 1,
  itemId: 'form',
  bodyPadding: 10,
  title: 'Actividad',

  layout: {
    type: 'vbox',
    align: 'stretch'
  },
  items: [
    {
      xtype: 'numberfield',
      fieldLabel: 'Código',
      name: 'codigo'
    },
    {
      xtype: 'textfield',
      fieldLabel: 'Nombre',
      name: 'nombre'
    }
  ],
  dockedItems: [
    {
      xtype: 'container',
      flex: 1,
      dock: 'bottom',
      layout: {
        type: 'hbox',
        align: 'stretch',
        pack: 'center'
      },
      items: [
        {
          xtype: 'button',
          handler: function(button, e) {
            f_crud.save_form(this.up('#form'));
          },
          margins: '',
          margin: 10,
          iconCls: 'x-fa fa-check',
          text: 'Aceptar'
        },
        {
          xtype: 'button',
          handler: function(button, e) {
            f_crud.close_form(this.up("#form"));
          },
          margin: 10,
          iconCls: 'x-fa fa-remove',
          text: 'Cancelar'
        }
      ]
    }
  ]

});