/*
 * File: app/view/ConfigMenu.js
 *
 * This file was generated by Sencha Architect version 4.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ConfigMenu', {
  extend: 'Ext.menu.Menu',
  alias: 'widget.configmenu',

  requires: [
    'MyApp.view.ConfigMenuViewModel'
  ],

  viewModel: {
    type: 'configmenu'
  },

  openCard: function(item, e) {
    var layout = MyApp.main.getLayout(), next,
        panelClass = item.panelClass,
        createPanel = function(panelClass) {
          var cardClass = "MyApp.view." + panelClass;
          if(Ext.ClassManager.get(cardClass)) {
            var newPan = Ext.create(cardClass);
            MyApp.main.add(newPan);
            MyApp.main.getLayout().next();
          }
          else {
            var errorMsg = "Error: Panel " + panelClass + " does not exist";
            throw errorMsg;
          }
        };
    layout.setActiveItem(0);
    next = layout.getNext();
    while(next) {
      next.close();
      next.destroy();
      next = layout.getNext();
    }
    createPanel(panelClass);
  }

});