/*
 * File: app/view/GridContainerTesting.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.GridContainerTesting', {
  extend: 'Ext.container.Viewport',
  alias: 'widget.gridcontainertesting',

  requires: [
    'MyApp.view.MainContainerViewModel2',
    'Ext.grid.Panel',
    'Ext.view.Table',
    'Ext.grid.column.Number',
    'Ext.form.field.Number',
    'Ext.grid.column.Date',
    'Ext.form.field.Date',
    'Ext.form.field.ComboBox',
    'Ext.grid.plugin.CellEditing'
  ],

  viewModel: {
    type: 'gridcontainertesting'
  },
  flex: 1,
  layout: 'card',
  defaultListenerScope: true,

  items: [
    {
      xtype: 'panel',
      title: 'GridEditing',
      items: [
        {
          xtype: 'gridpanel',
          title: 'My Grid Panel',
          store: 'GridEditing',
          columns: [
            {
              xtype: 'gridcolumn',
              dataIndex: 'fieldString',
              text: 'Field String',
              editor: {
                xtype: 'textfield'
              }
            },
            {
              xtype: 'numbercolumn',
              dataIndex: 'fieldInt',
              text: 'Field Int',
              format: '00',
              editor: {
                xtype: 'numberfield'
              }
            },
            {
              xtype: 'datecolumn',
              dataIndex: 'fieldDate',
              text: 'Field Date',
              format: 'm/j/Y',
              editor: {
                xtype: 'datefield'
              }
            },
            {
              xtype: 'gridcolumn',
              dataIndex: 'fieldComboboxString',
              text: 'Field Combobox String',
              editor: {
                xtype: 'textfield'
              }
            },
            {
              xtype: 'numbercolumn',
              dataIndex: 'fieldComboboxInt',
              text: 'Field Combobox Int',
              format: '00',
              editor: {
                xtype: 'combobox',
                displayField: 'fieldString',
                store: 'GridEditingField',
                valueField: 'fieldInt'
              }
            }
          ],
          plugins: [
            {
              ptype: 'cellediting'
            }
          ]
        }
      ]
    }
  ],
  listeners: {
    render: 'onViewportRender'
  },

  onViewportRender: function(component, eOpts) {
    f_crud.load_store('GridEditing');
    f_crud.load_store('GridEditingField');
  }

});