/*
 * File: app/view/LaboresForm.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LaboresForm', {
  extend: 'Ext.form.Panel',
  alias: 'widget.laboresform',

  requires: [
    'MyApp.view.LotesFormViewModel2',
    'Ext.container.Container',
    'Ext.button.Button',
    'Ext.form.field.Number'
  ],

  viewModel: {
    type: 'laboresform'
  },
  itemId: 'form',
  bodyPadding: 10,
  title: 'Lote',

  layout: {
    type: 'vbox',
    align: 'stretch'
  },
  dockedItems: [
    {
      xtype: 'container',
      dock: 'bottom',
      layout: {
        type: 'hbox',
        align: 'stretch',
        pack: 'center'
      },
      items: [
        {
          xtype: 'button',
          handler: function(button, e) {
            var laboresForm = this.up('#form');
            laboresForm.form._record.data.cod_lote_actividad = laboresForm.parent.codigo;
            laboresForm.form._record.data.cod_lote = laboresForm.parent.cod_lote;
            laboresForm.form._record.data.cod_periodo = laboresForm.parent.cod_periodo;
            var query = "select cod_establecimiento from Lotes where codigo = " + laboresForm.parent.cod_lote;
            console.log("Query statement: " + query);
            f_crud.sql_select(query, function(resultSet){
              if(resultSet === -1 || !Array.isArray(resultSet)) {
                console.log("Query statement: " + query);
                throw "Database error: Check your sql statement or your WebSql instance";
              }
              else {
                laboresForm.form._record.data.cod_establecimiento = resultSet[0].cod_establecimiento;
                //console.log(laboresForm);
                f_crud.save_form(laboresForm);
              }
            });
          },
          margins: '',
          margin: 10,
          iconCls: 'x-fa fa-check',
          text: 'Aceptar'
        },
        {
          xtype: 'button',
          handler: function(button, e) {
            f_crud.close_form(this.up("#form"));
          },
          margin: 10,
          iconCls: 'x-fa fa-remove',
          text: 'Cancelar'
        }
      ]
    }
  ],
  items: [
    {
      xtype: 'numberfield',
      fieldLabel: 'ID',
      name: 'id'
    }
  ]

});