/*
 * File: app/view/MainMenu.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainMenu', {
  extend: 'Ext.menu.Menu',
  alias: 'widget.mainmenu',

  requires: [
    'MyApp.view.ConfigMenuViewModel1'
  ],

  viewModel: {
    type: 'mainmenu'
  },

  openCard: function(item, e) {
    /*
    var thisPanel = MyApp.main.getLayout().getActiveItem();
    MyApp.main.getLayout().prev();
    thisPanel.close();
    */
    debugger;
    var panelClass = item.panelClass,
        createPanel = function(panelClass) {
          var cardClass = "MyApp.view." + panelClass;
          if(Ext.ClassManager.get(cardClass)) {
            var newPan = Ext.create(cardClass);
            MyApp.main.add(newPan);
            MyApp.main.getLayout().next();
          }
          else {
            var errorMsg = "Error: Panel " + panelClass + " does not exist";
            throw errorMsg;
          }
        };
    createPanel(panelClass);
  }

});