/*
 * File: app/view/Mensaje.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Mensaje', {
  extend: 'Ext.form.Panel',
  alias: 'widget.mensaje',

  requires: [
    'MyApp.view.LotesFormViewModel7',
    'Ext.form.Label',
    'Ext.form.Panel',
    'Ext.button.Button'
  ],

  viewModel: {
    type: 'mensaje'
  },
  itemId: 'form',
  scrollable: true,
  bodyPadding: 10,
  header: false,
  title: 'Informacion',
  defaultListenerScope: true,

  layout: {
    type: 'vbox',
    align: 'stretch'
  },
  items: [
    {
      xtype: 'label',
      flex: 1,
      html: 'Titl',
      itemId: 'title',
      text: 'My Label'
    },
    {
      xtype: 'form',
      flex: 1,
      html: '<p>Msg...</p>',
      itemId: 'mensaje',
      bodyPadding: 10,
      title: 'My Form'
    },
    {
      xtype: 'button',
      handler: function(button, e) {
        f_crud.close_form(this.up("#form"));
      },
      margin: 10,
      iconCls: 'x-fa fa-remove',
      text: 'Cerrar'
    }
  ],
  listeners: {
    activate: 'onFormActivate',
    hide: 'onFormHide'
  },

  onFormActivate: function(component, eOpts) {
    debugger;
    var item = component.header.title.text;
    if(component.action === 'ADD') {
      component.setTitle('Nuevo ' + item);
    }
    else if(component.action === 'EDIT') {
      component.setTitle('Editar ' + item);
    }
    else {
      component.setTitle(item);
    }
  },

  onFormHide: function(component, eOpts) {
    this.destroy();
  },

  f_mensaje: function(title, msg) {
    this.down('#title').setHtml(title);
    this.down('#mensaje').setHtml(msg);
  }

});