/*
 * File: app/model/GridEditing.js
 *
 * This file was generated by Sencha Architect version 4.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.GridEditing', {
  extend: 'Ext.data.Model',

  requires: [
    'Ext.data.field.String',
    'Ext.data.field.Integer',
    'Ext.data.field.Date'
  ],

  fields: [
    {
      type: 'string',
      name: 'fieldString'
    },
    {
      type: 'int',
      name: 'fieldInt'
    },
    {
      type: 'date',
      name: 'fieldDate'
    },
    {
      type: 'string',
      name: 'fieldComboboxString'
    },
    {
      type: 'int',
      name: 'fieldComboboxInt'
    }
  ]
});